---
title: "sgma"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sgma}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::install_github("govscienceuseR/citationClassify")
library(citationClassify)
packs = c('data.table', 'dplyr', 'stringr')
sapply(packs, require, character.only = T)
```

```{r}
dt <- fread("~/Box/citation_classifier/data/gsp_references_clean.csv")
```

```{r}
table(journal_match(dt$container))
```

```{r}
table(conference_match(dt$container))
```

```{r}
table(agency_match(dt$container, dt$author))
```
```{r}
dt <- prepared_by(dt, x = 'container', y = 'author', z = 'publisher')
```

```{r}
dt$journal_disam <- journal_disambig(dt$container)
```

```{r}
table(journal_match(dt$journal_disam))
```

```{r}
table(conference_match(dt$journal_disam))
```

```{r}
table(agency_match(dt$journal_disam, dt$author))
```

```{r}
dt <- regex_classify(dt, 'journal_disam')
```

